spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webflux.routes[0].id=partida-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PARTIDA-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/partidas,/api/partidas/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[1].id=noticia-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://NOTICIA-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/noticias,/api/noticias/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}