spring.application.name=noticia-service

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.data.mongodb.uri=mongodb://localhost:27017/noticias_db

management.endpoints.web.exposure.include=health,info,metrics

resilience4j.circuitbreaker.instances.partidaService.sliding-window-size=2
resilience4j.circuitbreaker.instances.partidaService.minimum-number-of-calls=1
resilience4j.circuitbreaker.instances.partidaService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.partidaService.wait-duration-in-open-state=10s

spring.cloud.openfeign.circuitbreaker.enabled=true